#!/usr/bin/env bash
set -euo pipefail

# Bash Special Chars
# ------------------
# ' - Q  quote
# " - QQ double-quote
# ` - T  tick
# # - H  hash
# $ - D  dollar sign
# & - A  ampersand
# * - S  star
# ( - B  bracket (open)
# ) - B  bracket (close)
# | - P  pipe
# \ - B  backslash
# : - C  colon (not strictly necessary, but nice for parity with semicolon)
# ; - SC semicolon
# < - LT less-than
# < - LC left-caret (alias)
# > - GT greater-than
# > - RC right-caret (alias)

function jostar() (
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "-help" ]]; then
    echo "The jo* usage manual is coming -- please check back soon!"
    echo "Sorry jo* doesn't have good documentation quite yet."
    exit 0
  fi

  local origdir
  local message="$*"

  # if no JOTS file in current directory, nav up until we find one
  origdir="$( pwd )"
  while ! ls ./JOTS* 1> /dev/null 2>&1; do
    if [[ "$( pwd )" == "${HOME}" ]]; then
      cd "${origdir}" || exit
      break
    else
      cd ..
    fi
  done

  # remove jot by index:
  if [[ "${message}" =~ ^[0-9]+$ ]]; then
    for file in JOTS*; do
      if [[ -f "${file}" ]]; then
        sed -i '' "${message}d" "${file}"
      fi
    done

  # swap jots by index:
  elif [[ "${message}" =~ ^[0-9]+[[:space:]][0-9]+$ ]]; then
    for file in JOTS*; do
      if [[ -f "${file}" ]]; then
        local a
        local b
        a="$1"
        b="$2"
        if (( a > b )); then
          local temp
          temp="${a}"
          a="${b}"
          b="${temp}"
        fi
        if (( a != b)); then
          {
              printf '%dm%d\n' "${a}" "${b}"
              printf '%d-m%d-\n' "${b}" "${a}"
              printf '%s\n' w q
          } | ed -s "${file}"
        fi
      fi
    done

  # create jot (if message provided):
  elif [[ -n "${message}" ]]; then
    local jofile
    for file in JOTS*; do
      if [[ -f "${file}" ]]; then
        jofile="${file}"
        break
      fi
    done
    if ! [[ -f "${jofile}" ]]; then
      jofile="JOTS"
    fi
    echo "${message}" >> "${jofile}"
  fi

  # list jots
  for file in JOTS*; do
    if [[ -f "${file}" ]]; then
      if [[ -s "${file}" ]]; then
        cat -n "${file}"
      else
        echo " All done, time for a bizzare adventure."
      fi
    fi
  done
)

jostar "$@"
